import { MediaObject } from '@starlightcms/js-sdk'
import { RefObject } from 'react'

/**
 * Props accepted by the {@link ResponsiveImage} component.
 * @group ResponsiveImage
 */
export interface ResponsiveImageProps {
  className?: string
  /**
   * The image to render. It should be a URI string or the object returned by
   * Starlight on a Media File field. Required.
   */
  image: MediaObject | string
  /**
   * An HTML <img> `sizes` attribute. If provided, the browser will render the
   * best fit image size variation to the current viewport size. See
   * [the MDN documentation on the sizes property](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes)
   * to learn how to configure this attribute.
   */
  sizes?: string
  /**
   * Alternate text description of the image. If set and the given image is a
   * Starlight media object, it will overwrite this image's alternative text
   * set in Starlight.
   */
  alt?: string
  /**
   * Defines which image variation will be rendered. Defaults to `optimized`.
   */
  variation?: string
  /**
   * Defines the background color of the image while it loads. It accepts any
   * CSS color, including `transparent`. Defaults to the color generated by
   * Starlight when the image was uploaded, or transparent when the given image
   * is a URI string.
   */
  background?: string
  /**
   * Defines the scrollable parent of the image. Set this to the nearest
   * scrollable HTMLElement parent of this image if lazy-loading is not working.
   * See [the MDN documentation on IntersectionObserver.root](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/root)
   * to learn more.
   */
  lazyRoot?: RefObject<HTMLElement> | null
  /**
   * Defines how close to the viewport an image has to be to start loading.
   * See [the MDN documentation on IntersectionObserver.rootMargin](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/rootMargin)
   * to learn more. Defaults to 200px.
   */
  lazyRootMargin?: string
}
